version: '3.8'

services:
  app:
    build: ./
    environment:
      MY_EXAMPLE_INJECTED_SECRET_KEY: some-placeholder-value
      NODE_ENV: development
    ports:
      - 8080:8080
    volumes:
      - ./:/app

  terraform:
    image: 1mill/terraform-sops:alpine-2020-07-16T02-22-23
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      AWS_PROFILE: ${AWS_PROFILE}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    volumes:
      - ./:/app
