version: '3.8'

services:
  app:
    build: .
    environment:
      MY_EXAMPLE_INJECTED_SECRET_KEY: some-placeholder-value
      NODE_ENV: development
    ports:
      - 8080:8080
    volumes:
      - ./:/app
