name: CI/CD

on: [pull_request, push]

jobs:
  services:
    runs-on: ubuntu-20.04
    outputs:
      services: ${{ steps.output_services.outputs.services }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - run: echo ::set-output name=services::$(git diff-tree --no-commit-id --dirstat=files,0 -r ${{ github.sha }} | sed 's/^[ 0-9.]\+% //g' | xargs)
        id: output_services

  test:
    needs: [services]
    strategy:
      matrix:
        services: ${{ needs.services.outputs.services }}
      fail-fast: true
    runs-on: ubuntu-20.04
    steps:
      - run: echo ${{ needs.services.outputs.services }}

