name: services_my-application_CI

on:
  push:
    paths:
      - services/my-application/*

defaults:
  run:
    shell: bash
    working-directory: ./services/my-application

jobs:
  package:
    env:
      IMAGENAME: services-my-application
      IMAGEREGISTRY: hub.docker.com:443
      PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
    if: endsWith(github.ref, 'master') == true
    runs-on: ubuntu-20.04
    outputs:
      version: ${{ steps.output_version.outputs.VERSION }}
    steps:
      - uses: actions/checkout@v2
      - run: echo "::set-env name=VERSION::$(date +'%Y-%m-%dT%H-%M-%S')"
      - run: echo "::set-output name=VERSION::${{ env.VERSION }}"
        id: output_version
      - run: echo "${PASSWORD}" | docker login --username ${USERNAME} --password-stdin
      - run: docker build . --file Dockerfile --tag temp-image
      - run: docker tag temp-image ${IMAGEREGISTRY}/${USERNAME}/${IMAGENAME}:${VERSION}
      - run: docker tag temp-image ${IMAGEREGISTRY}/${USERNAME}/${IMAGENAME}:latest
      - run: docker push ${IMAGEREGISTRY}/${USERNAME}/${IMAGENAME}:${VERSION}
      - run: docker push ${IMAGEREGISTRY}/${USERNAME}/${IMAGENAME}:latest
