name: CI/CD

on: [pull_request, push]

jobs:
  get-commit-diffs:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: echo "::set-env name=ANOTHER_TEMP_VAR::$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | xargs)"
      - run: echo ${{ env.ANOTHER_TEMP_VAR }}
      - run: echo ::set-env name=TEMP_VAR::$(git diff --dirstat=files,0 ${{ github.event.before }} ${{ github.sha }} | sed 's/^[ 0-9.]\+% //g')
      - run: echo $TEMP_VAR
      - run: echo ${{ env.TEMP_VAR }}

  try-market-action:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: technote-space/get-diff-action@v2
        id: git_diff
        with:
          PREFIX_FILTER: level-1/
          SUFFIX_FILTER: '.txt'
      - run: |
          array=(${{ steps.git_diff.outputs.diff }})
          for i in "${array[@]}"
          do
            echo $i
          done
        if: steps.git_diff.outputs.diff

