name: CI/CD

on: [pull_request, push]

jobs:
  services:
    runs-on: ubuntu-20.04
    outputs:
      services: ${{ steps.output_services.outputs.services }}
    steps:
      - run: apt-get update && apt-get install --yes jq
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - run: echo ::set-output name=services::$(git diff-tree --no-commit-id --dirstat=files,0 -r 086c022 | sed 's/^[ 0-9.]\+% //g' | jq --raw-input --slurp 'split("\n")' | jq -c 'map(select(. | contains("level")))')
        id: output_services

  test:
    needs: [services]
    runs-on: ubuntu-20.04
    steps:
      - run: echo ${{ needs.services.outputs.services }}
    strategy:
      matrix:
        services: ${{ needs.services.outputs.services }}
      fail-fast: true

