name: CI/CD

on: [pull_request, push]

jobs:
  get-commit-diffs:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: |
          arr=$(git diff --dirstat=files,0 ${{ github.ref }} ${{ github.sha }} | sed 's/^[ 0-9.]\+% //g')
          echo ${arr}
        shell: bash

  try-market-action:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: technote-space/get-diff-action@v2
        id: git_diff
        with:
          PREFIX_FILTER: level-1/
          SUFFIX_FILTER: '.txt'
      - run: |
          files=${{ steps.git_diff.outputs.diff }}
          for i in "${files[@]}"; do
            echo "${i}"
          end
        if: steps.git_diff.outputs.diff

