name: CI/CD

on: [pull_request, push]

jobs:
  get-commit-diffs:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: echo "::set-env name=TEMP_VAR::$(git diff --dirstat=files,0 ${{ github.event.before }} ${{ github.sha }} | sed 's/^[ 0-9.]\+% //g')"
      - run: echo {{ env.TEMP_VAR }}

      # - run: array=$(git diff --dirstat=files,0 ${{ github.event.before }} ${{ github.sha }} | sed 's/^[ 0-9.]\+% //g')
      # - run: echo $array
      # - run: for i in $arr; do echo $i; done
