name: services_my-application_CI

on:
  push:
    paths:
      - services/my-application/*

defaults:
  run:
    shell: bash
    working-directory: ./services/my-application

jobs:
  package:
    env:
      IMAGE_NAME: services-my-application
      REGISTROY_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      REGISTROY_URL: docker.io
      REGISTRY_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
    if: endsWith(github.ref, 'master') == true
    runs-on: ubuntu-20.04
    outputs:
      version: ${{ steps.output_version.outputs.VERSION }}
    steps:
      - uses: actions/checkout@v2
      - run: echo "::set-env name=VERSION::$(date +'%Y-%m-%dT%H-%M-%S')"
      - run: echo "::set-output name=VERSION::${{ env.VERSION }}"
        id: output_version
      - run: echo "${REGISTROY_PASSWORD}" | docker login --username ${REGISTRY_USERNAME} --password-stdin
      - run: docker build . --file Dockerfile --tag temp-image
      - run: docker tag temp-image ${REGISTROY_URL}/${REGISTRY_USERNAME}/${IMAGE_NAME}:${VERSION}
      - run: docker tag temp-image ${REGISTROY_URL}/${REGISTRY_USERNAME}/${IMAGE_NAME}:latest
      - run: docker push ${REGISTROY_URL}/${REGISTRY_USERNAME}/${IMAGE_NAME}:${VERSION}
      - run: docker push ${REGISTROY_URL}/${REGISTRY_USERNAME}/${IMAGE_NAME}:latest
